version: '3'

services:
  flightlogs:
    container_name: flightlogs
    build: .
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: flightlogs
      SLEEP_TIME: 5

networks:
  default:
    external:
      name: kafka-network
